import { css } from '@/styled-system/css';

export const navbarStyles = {
  shell: css({
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    width: '100%',
    zIndex: 10000,
    display: 'flex',
    justifyContent: 'center',
    overflow: 'hidden',
    pointerEvents: 'none',
    '@media (max-width: 768px)': {
      paddingX: '0',
    },
  }),

  overlay: css({
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100vw',
    height: '100vh',
    background: 'transparent',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-start',
    padding: { base: '12px !important', md: '16px !important' },
  }),

  canvas: css({
    width: '100%',
    maxWidth: '500px',
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    minHeight: 0,
  }),

  navbar: css({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    maxWidth: '500px',
    borderRadius: { base: '12px', md: '16px' },
    padding: { base: '8px 16px !important', md: '10px 20px !important' },
    backdropFilter: 'blur(12px) saturate(180%)',
    background: 'rgba(255, 255, 255, 0.08)',
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.12), 0 2px 8px rgba(0, 0, 0, 0.08)',
    color: '#fff',
    pointerEvents: 'auto',
  }),

  menuToggle: css({
    border: 'none',
    background: 'transparent',
    color: '#fff',
    fontSize: { base: '0.75rem', md: '0.9rem' },
    fontWeight: 700,
    letterSpacing: { base: '0.2em', md: '0.25em' },
    textTransform: 'uppercase',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  }),

  menuList: css({
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '10px',
    width: '100%',
    borderRadius: '20px',
    padding: '28px !important',
    backdropFilter: 'blur(12px) saturate(180%)',
    background: 'rgba(255, 255, 255, 0.08)',
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.12), 0 2px 8px rgba(0, 0, 0, 0.08)',
    textAlign: 'center',
    overflow: 'hidden',
    minHeight: 0,
  }),

  menuItem: css({
    width: '100%',
  }),

  menuItemInner: css({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    padding: '6px 0',
    borderRadius: '12px',
    color: '#5A5A5A',
    textDecoration: 'none',
    textTransform: 'uppercase',
    fontWeight: 800,
    letterSpacing: '-0.03em',
    fontSize: { base: '1.8rem', md: '2.2rem' },
    lineHeight: 0.8,
    textAlign: 'center',
    transition: 'color 0.2s ease',
    '&[data-active="true"]': {
      color: '#FFFFFF',
    },
  }),

  menuItemTitle: css({
    fontSize: 'inherit',
    fontWeight: 'inherit',
    letterSpacing: 'inherit',
    color: 'inherit',
  }),

  metaRow: css({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    borderRadius: '20px',
    padding: '16px !important',
    backdropFilter: 'blur(12px) saturate(180%)',
    background: 'rgba(255, 255, 255, 0.08)',
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.12), 0 2px 8px rgba(0, 0, 0, 0.08)',
    color: 'rgba(255,255,255,0.65)',
    fontSize: { base: '0.75rem', md: '0.85rem' },
    letterSpacing: '0.08em',
  }),

  localeRow: css({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    borderRadius: '20px',
    padding: '18px 28px !important',
    backdropFilter: 'blur(12px) saturate(180%)',
    background: 'rgba(255, 255, 255, 0.08)',
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.12), 0 2px 8px rgba(0, 0, 0, 0.08)',
    color: 'rgba(255,255,255,0.65)',
    fontSize: { base: '0.85rem', md: '0.95rem' },
    letterSpacing: '0.08em',
    gap: '10px',
    flexWrap: 'wrap',
  }),

  localeButton: css({
    border: 'none',
    background: 'transparent',
    color: '#5A5A5A',
    fontSize: { base: '0.8rem', md: '0.9rem' },
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'color 0.2s ease',
    '&[data-active="true"]': {
      color: '#FFFFFF',
    },
  }),

  loginButton: css({
    border: 'none',
    background: '#FFFFFF',
    borderRadius: '999px',
    padding: '8px 20px !important',
    fontSize: '0.9rem',
    fontWeight: 600,
    letterSpacing: '0.15em',
    textTransform: 'uppercase',
    color: '#000000',
    cursor: 'pointer',
    textDecoration: 'none',
    transition: 'background 0.2s ease, transform 0.2s ease',
    _hover: {
      background: 'rgba(255,255,255,0.9)',
      transform: 'scale(1.05)',
    },
  }),

  logoutButton: css({
    border: 'none',
    background: 'transparent',
    borderRadius: '999px',
    padding: '8px 20px',
    fontSize: '0.9rem',
    fontWeight: 600,
    letterSpacing: '0.15em',
    textTransform: 'uppercase',
    color: '#F11313',
    cursor: 'pointer',
    transition: 'color 0.2s ease, transform 0.2s ease',
    _hover: {
      color: '#ff3333',
      transform: 'scale(1.05)',
    },
  }),

  adminDivider: css({
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '10px',
    marginTop: '8px',
    marginBottom: '4px',
    opacity: 0.7,
  }),

  adminDividerLine: css({
    flex: 1,
    height: '1px',
    background: 'rgba(255,255,255,0.15)',
  }),

  adminDividerLabel: css({
    fontSize: '0.75rem',
    letterSpacing: '0.18em',
    textTransform: 'uppercase',
    color: 'rgba(255,255,255,0.7)',
    whiteSpace: 'nowrap',
  }),
};
