import { css } from '@/styled-system/css';

export const shareCheckoutSelectorStyles = {
    wrapper: css({
        width: '100%',
        maxWidth: '100%',
        display: 'flex',
        justifyContent: 'center',
        boxSizing: 'border-box',
    }),
    stack: css({
        width: '100%',
        maxW: { base: '100%', sm: '380px', md: '420px' },
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: { base: '8px', sm: '12px' },
        color: '#f4f2ef',
        boxSizing: 'border-box',
    }),
    cardPrimary: css({
        width: '100%',
        maxWidth: '100%',
        borderRadius: { base: '20px', sm: '28px' },
        background: 'rgba(8, 8, 8, 0.9)',
        border: '1px solid rgba(255, 255, 255, 0.08)',
        padding: { base: '14px', sm: '20px' },
        display: 'flex',
        flexDirection: 'column',
        gap: { base: '10px', sm: '16px' },
        position: 'relative',
        boxSizing: 'border-box',
    }),
    propertyRow: css({
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: '12px',
    }),
    propertyInfo: css({
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
    }),
    propertyTitle: css({
        fontSize: { base: '0.9rem', sm: '1rem' },
        fontWeight: 600,
        overflowWrap: 'break-word',
        wordBreak: 'break-word',
    }),
    propertyMeta: css({
        fontSize: { base: '0.75rem', sm: '0.85rem' },
        color: 'rgba(244, 242, 239, 0.65)',
        overflowWrap: 'break-word',
        wordBreak: 'break-word',
    }),
    actionChip: css({
        borderRadius: '999px',
        background: 'rgba(255,255,255,0.08)',
        border: '1px solid rgba(255,255,255,0.12)',
        color: '#f4f2ef',
        paddingInline: '14px',
        paddingBlock: '6px',
        fontSize: '0.8rem',
        fontWeight: 600,
        cursor: 'pointer',
        transition: 'background 0.2s ease',
        _hover: { background: 'rgba(255,255,255,0.15)' },
    }),
    divider: css({
        width: '100%',
        height: '1px',
        background: 'rgba(255,255,255,0.06)',
    }),
    inputShell: css({
        width: '100%',
        display: 'flex',
        flexDirection: 'column',
        gap: { base: '8px', sm: '12px' },
        alignItems: 'center',
    }),
    valueRow: css({
        width: '100%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: { base: '10px', sm: '18px' },
    }),
    valueDisplay: css({
        position: 'relative',
        flex: '0 1 auto',
        minWidth: { base: '100px', sm: '140px' },
        height: { base: '52px', sm: '72px' },
    }),
    inputWrapper: css({
        position: 'relative',
        width: '100%',
        height: '100%',
    }),
    inputField: css({
        position: 'absolute',
        inset: 0,
        width: '100%',
        height: '100%',
        textAlign: 'center',
        fontSize: { base: '32px', sm: '48px' },
        fontWeight: 600,
        letterSpacing: '-1px',
        lineHeight: { base: '52px', sm: '72px' },
        color: 'transparent',
        caretColor: '#f4f2ef',
        background: 'transparent',
        border: 'none',
        outline: 'none',
        cursor: 'text',
        padding: 0,
    }),
    digitsLayer: css({
        position: 'absolute',
        inset: 0,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        gap: '4px',
        pointerEvents: 'none',
    }),
    digitsValue: css({
        display: 'flex',
        gap: '2px',
        alignItems: 'center',
        pointerEvents: 'none',
    }),
    digitChar: css({
        fontSize: { base: '32px', sm: '48px' },
        fontWeight: 600,
        letterSpacing: '-1px',
        lineHeight: 1,
        color: '#f4f2ef',
    }),
    summaryRow: css({
        width: '100%',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        minHeight: { base: '32px', sm: '40px' },
    }),
    stepControls: css({
        width: '100%',
        maxWidth: '100%',
        textAlign: 'center',
        fontSize: { base: '0.65rem', sm: '0.85rem' },
        color: 'rgba(244, 242, 239, 0.7)',
        overflowWrap: 'break-word',
        wordBreak: 'break-word',
        paddingInline: { base: '4px', sm: '0' },
        boxSizing: 'border-box',
    }),
    stepButton: css({
        width: { base: '36px', sm: '44px' },
        height: { base: '36px', sm: '44px' },
        borderRadius: { base: '12px', sm: '18px' },
        border: '1px solid rgba(255,255,255,0.15)',
        background: 'rgba(250,250,250,0.08)',
        color: '#f4f2ef',
        fontSize: { base: '1.1rem', sm: '1.3rem' },
        fontWeight: 600,
        cursor: 'pointer',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        backdropFilter: 'blur(8px)',
        transition: 'background 0.2s ease, transform 0.2s ease',
        flexShrink: 0,
        _hover: { background: 'rgba(255,255,255,0.18)' },
        _disabled: { opacity: 0.35, cursor: 'not-allowed', transform: 'none' },
    }),
    conversionRow: css({
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        padding: '8px 12px',
        borderRadius: '999px',
        background: 'rgba(255,255,255,0.04)',
        border: '1px solid rgba(255,255,255,0.08)',
    }),
    iconBadge: css({
        width: '32px',
        height: '32px',
        borderRadius: '999px',
        background: 'rgba(255,255,255,0.08)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    }),
    secondaryCard: css({
        width: '100%',
        maxWidth: '100%',
        borderRadius: { base: '18px', sm: '26px' },
        background: 'rgba(14,14,14,0.85)',
        border: '1px solid rgba(255,255,255,0.06)',
        padding: { base: '16px 14px 20px', sm: '20px 18px 24px' },
        display: 'flex',
        flexDirection: 'column',
        gap: { base: '10px', sm: '14px' },
        boxSizing: 'border-box',
    }),
    secondaryHeader: css({
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
    }),
    secondaryLabel: css({
        fontSize: { base: '0.75rem', sm: '0.9rem' },
        color: 'rgba(244, 242, 239, 0.7)',
        overflowWrap: 'break-word',
    }),
    numberEmphasis: css({
        fontSize: { base: '1.1rem', sm: '1.4rem' },
        fontWeight: 600,
    }),
    secondaryFoot: css({
        fontSize: { base: '0.75rem', sm: '0.85rem' },
        color: 'rgba(244, 242, 239, 0.55)',
        overflowWrap: 'break-word',
        wordBreak: 'break-word',
        lineHeight: 1.5,
        whiteSpace: 'normal',
        marginTop: { base: '2px', sm: '4px' },
    }),
    tipIcon: css({
        width: { base: '32px', sm: '40px' },
        height: { base: '32px', sm: '40px' },
        borderRadius: { base: '10px', sm: '14px' },
        background: 'rgba(255,255,255,0.06)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    }),
    paymentButton: css({
        width: '100%',
        borderRadius: '999px',
        paddingBlock: { base: '14px', sm: '16px' },
        background: 'linear-gradient(120deg,#ffffff,#cfcfcf)',
        color: '#050505',
        fontWeight: 600,
        fontSize: { base: '0.9rem', sm: '1rem' },
        border: 'none',
        cursor: 'pointer',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '8px',
        transition: 'transform 0.2s ease, box-shadow 0.2s ease',
        marginTop: { base: '8px', sm: '12px' },
        _hover: {
            transform: 'translateY(-1px)',
            boxShadow: '0 10px 15px rgba(255,255,255,0.25)',
        },
        _disabled: {
            opacity: 0.4,
            cursor: 'not-allowed',
            transform: 'none',
            boxShadow: 'none',
        },
    }),
    hint: css({
        width: '100%',
        maxWidth: '100%',
        fontSize: { base: '0.7rem', sm: '0.8rem' },
        textAlign: 'center',
        color: 'rgba(244, 242, 239, 0.6)',
        lineHeight: 1.4,
        overflowWrap: 'break-word',
        wordBreak: 'break-word',
        paddingInline: { base: '8px', sm: '0' },
        marginTop: { base: '4px', sm: '8px' },
        boxSizing: 'border-box',
    }),
    notice: css({
        fontSize: '0.78rem',
        color: '#f87171',
        textAlign: 'center',
    }),
    chevron: css({
        padding: '6px',
        borderRadius: '999px',
        background: 'rgba(8, 8, 8, 0.9)',
        border: '1px solid rgba(255,255,255,0.08)',
    }),
    connector: css({
        position: 'absolute',
        bottom: { base: '-18px', sm: '-25px' },
        left: '50%',
        transform: 'translateX(-50%)',
        zIndex: 99,
        width: '100%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    }),
};

