import { css } from '@/styled-system/css';

export const featuredLaunchStyles = {
  section: css({
    width: '100%',
    position: 'relative',
    zIndex: 5,
    isolation: 'isolate',
    color: '#f5f4f3',
    display: 'flex',
    justifyContent: 'center',
  }),
  content: css({
    display: 'flex',
    flexDirection: { base: 'column', lg: 'row' },
    alignItems: 'center',
    justifyContent: 'center',
    gap: { base: '24px', sm: '32px', md: '40px', lg: '48px', xl: '56px' },
    width: '100%',
    maxW: '1400px',
    border: '1px solid rgba(255, 255, 255, 0.3)',
    borderRadius: { base: '20px', sm: '24px', md: '28px', lg: '32px', xl: '36px' },
  }),
  mediaPanel: css({
    position: 'relative',
    width: '100%',
    maxW: { base: '100%', sm: '320px', md: '380px', lg: '420px', xl: '480px' },
    aspectRatio: '1 / 1',
    borderRadius: { base: '20px', sm: '24px', md: '28px', lg: '32px', xl: '36px' },
    overflow: 'hidden',
    isolation: 'isolate',
    bg: '#0d0d0c',
    boxShadow: { base: '0 15px 40px rgba(0,0,0,0.45)', md: '0 25px 60px rgba(0,0,0,0.55)' },
    alignSelf: 'center',
  }),
  mediaImage: css({
    position: 'absolute',
    inset: 0,
    w: '100%',
    h: '100%',
    objectFit: 'cover',
    transform: 'scale(1.05)',
    filter: 'blur(16px)',
    opacity: 0.9,
    transition: 'filter 0.8s cubic-bezier(0.4, 0, 0.2, 1), transform 0.8s cubic-bezier(0.4, 0, 0.2, 1), opacity 0.8s cubic-bezier(0.4, 0, 0.2, 1)',
  }),
  mediaImageClear: css({
    position: 'absolute',
    inset: 0,
    w: '100%',
    h: '100%',
    objectFit: 'cover',
    transform: 'scale(1)',
    filter: 'none',
    opacity: 1,
    transition: 'filter 0.8s cubic-bezier(0.4, 0, 0.2, 1), transform 0.8s cubic-bezier(0.4, 0, 0.2, 1), opacity 0.8s cubic-bezier(0.4, 0, 0.2, 1)',
  }),
  mediaOverlay: css({
    position: 'absolute',
    inset: 0,
    bgGradient: 'linear(to-b, rgba(5, 3, 3, 0.25), rgba(5, 3, 3, 0.9))',
    backdropFilter: 'blur(12px)',
  }),
  mediaContent: css({
    position: 'relative',
    zIndex: 1,
    h: '100%',
    overflow: 'hidden',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: { base: '16px', sm: '20px', md: '24px', lg: '28px', xl: '32px' },
    textAlign: 'center',
    borderRadius: { base: '20px', sm: '24px', md: '28px', lg: '32px', xl: '36px' },
    border: '1px solid rgba(255,255,255,0.05)',
  }),
  mediaContentLive: css({
    position: 'relative',
    zIndex: 1,
    h: '100%',
    overflow: 'hidden',
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'flex-start',
    padding: { base: '16px', sm: '20px', md: '24px', lg: '28px', xl: '32px' },
    textAlign: 'left',
    borderRadius: { base: '20px', sm: '24px', md: '28px', lg: '32px', xl: '36px' },
    border: 'none',
    background: 'linear-gradient(180deg, transparent 0%, transparent 50%, rgba(0,0,0,0.4) 100%)',
  }),
  notificationContainer: css({
    position: 'absolute',
    top: { base: '12px', sm: '14px', md: '18px', lg: '20px', xl: '24px' },
    right: { base: '12px', sm: '14px', md: '18px', lg: '20px', xl: '24px' },
    zIndex: 2,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-end',
    gap: { base: 2, md: 3 },
  }),
  notificationDropdown: css({
    minW: { base: '200px', sm: '220px', md: '240px' },
    maxW: { base: 'calc(100vw - 48px)', sm: 'none' },
    padding: { base: '14px', sm: '16px', md: '18px' },
    borderRadius: { base: 16, md: 20 },
    border: '1px solid rgba(255,255,255,0.15)',
    background: 'rgba(5,5,5,0.75)',
    backdropFilter: 'blur(18px)',
    boxShadow: { base: '0 15px 30px rgba(0,0,0,0.4)', md: '0 20px 40px rgba(0,0,0,0.45)' },
    display: 'flex',
    flexDirection: 'column',
    gap: { base: 3, md: 4 },
  }),
  dropdownTitle: css({
    fontSize: '0.85rem',
    letterSpacing: '0.2em',
    textTransform: 'uppercase',
    color: 'rgba(255,255,255,0.75)',
  }),
  dropdownSubtitle: css({
    fontSize: '0.8rem',
    color: 'rgba(255,255,255,0.65)',
    lineHeight: 1.5,
  }),
  dropdownOptions: css({
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  }),
  dropdownOption: css({
    borderRadius: '14px',
    border: '1px solid rgba(255,255,255,0.15)',
    padding: '10px 14px !important',
    background: 'rgba(255,255,255,0.02)',
    color: '#f5f4f3',
    fontSize: '0.8rem',
    letterSpacing: '0.15em',
    textTransform: 'uppercase',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    textAlign: 'center',
    _hover: {
      borderColor: '#f5f4f3',
      background: 'rgba(255,255,255,0.08)',
    },
  }),
  dropdownOptionActive: css({
    background: '#ff3828',
    borderColor: '#ff3828',
    color: '#fff',
    boxShadow: '0 18px 35px rgba(255,56,40,0.35)',
  }),
  dropdownOptionDisabled: css({
    opacity: 0.35,
    cursor: 'not-allowed',
    pointerEvents: 'none',
  }),

  // Now Available state - Apple iOS 26 style
  liveBadgeTopRight: css({
    position: 'absolute',
    top: { base: '12px', sm: '16px', md: '20px' },
    right: { base: '12px', sm: '16px', md: '20px' },
    zIndex: 3,
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    padding: { base: '8px 14px', md: '10px 18px' },
    borderRadius: '999px',
    background: 'rgba(0, 0, 0, 0.5)',
    backdropFilter: 'blur(24px) saturate(180%)',
    border: '1px solid rgba(255, 255, 255, 0.15)',
  }),
  liveDot: css({
    width: { base: '8px', md: '10px' },
    height: { base: '8px', md: '10px' },
    borderRadius: '50%',
    background: '#34c759',
    boxShadow: '0 0 8px rgba(52, 199, 89, 0.8), 0 0 16px rgba(52, 199, 89, 0.4)',
    animation: 'livePulse 2s ease-in-out infinite',
  }),
  liveText: css({
    fontSize: { base: '0.75rem', md: '0.8rem' },
    fontWeight: 500,
    letterSpacing: '0.02em',
    color: 'rgba(255, 255, 255, 0.95)',
  }),
  liveTagline: css({
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: { base: '0.7rem', md: '0.75rem' },
    fontWeight: 500,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: '#34c759',
    alignSelf: { base: 'center', lg: 'flex-start' },
    _before: {
      content: '""',
      display: 'block',
      width: '6px',
      height: '6px',
      borderRadius: '50%',
      background: '#34c759',
      boxShadow: '0 0 6px rgba(52, 199, 89, 0.6)',
      animation: 'livePulse 2s ease-in-out infinite',
    },
  }),
  liveCtaContainer: css({
    display: 'flex',
    flexDirection: 'column',
    gap: { base: '10px', md: '12px' },
    marginTop: { base: '20px', md: '28px' },
    alignItems: { base: 'center', lg: 'flex-start' },
    width: '100%',
  }),
  liveUrgency: css({
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: { base: 'center', lg: 'flex-start' },
    gap: '8px',
    marginTop: { base: '8px', md: '12px' },
    fontSize: { base: '0.75rem', md: '0.8rem' },
    fontWeight: 500,
    letterSpacing: '0.03em',
    color: 'rgba(255, 255, 255, 0.55)',
    '& svg': {
      color: '#34c759',
      flexShrink: 0,
      animation: 'livePulse 2s ease-in-out infinite',
    },
  }),
  liveCta: css({
    display: 'inline-flex',
    alignItems: 'center',
    gap: { base: '10px', md: '12px' },
    padding: { base: '14px 24px', md: '16px 32px' },
    borderRadius: '999px',
    border: 'none',
    background: '#ffffff',
    color: '#0a0a0a',
    fontSize: { base: '0.85rem', md: '0.9rem' },
    fontWeight: 600,
    letterSpacing: '0.02em',
    cursor: 'pointer',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    boxShadow: '0 4px 20px rgba(255, 255, 255, 0.15)',
    _hover: {
      transform: 'translateY(-2px)',
      boxShadow: '0 8px 30px rgba(255, 255, 255, 0.25)',
    },
    _active: {
      transform: 'translateY(0)',
    },
    '& svg': {
      transition: 'transform 0.3s ease',
    },
    '&:hover svg': {
      transform: 'translateX(4px)',
    },
  }),
  liveCtaOverlay: css({
    position: 'absolute',
    bottom: { base: '12px', sm: '16px', md: '20px' },
    left: { base: '12px', sm: '16px', md: '20px' },
    right: { base: '12px', sm: '16px', md: '20px' },
    zIndex: 3,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: { base: '10px', md: '12px' },
    padding: { base: '16px 24px', md: '18px 32px' },
    borderRadius: { base: '16px', md: '20px' },
    border: 'none',
    background: 'rgba(255, 255, 255, 0.95)',
    backdropFilter: 'blur(12px)',
    color: '#0a0a0a',
    fontSize: { base: '1.2rem', md: '1.2rem' },
    lineHeight: 0.8,
    fontFamily: 'var(--font-bebas-neue), sans-serif',
    cursor: 'pointer',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.25), 0 2px 8px rgba(0, 0, 0, 0.15)',
    _hover: {
      background: '#ffffff',
      transform: 'translateY(-2px)',
      boxShadow: '0 12px 40px rgba(0, 0, 0, 0.3), 0 4px 12px rgba(0, 0, 0, 0.2)',
    },
    _active: {
      transform: 'translateY(0)',
    },
    '& svg': {
      transition: 'transform 0.3s ease',
    },
    '&:hover svg': {
      transform: 'translateX(4px)',
    },
  }),

  detailsPanel: css({
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: { base: 3, sm: 4, md: 5 },
    width: '100%',
    textAlign: { base: 'center', lg: 'left' },
    padding: { base: '0', lg: '0 0 0 16px' },
  }),
  badge: css({
    alignSelf: 'flex-start',
    textTransform: 'uppercase',
    letterSpacing: '0.35em',
    fontSize: '0.65rem',
    color: 'rgba(255,255,255,0.55)',
    border: '1px solid rgba(255,255,255,0.2)',
    borderRadius: '999px',
    px: 4,
    py: 2,
  }),
  title: css({
    fontFamily: 'var(--font-bebas-neue), sans-serif',
    fontSize: { base: '2rem', sm: '2.5rem', md: '3rem', lg: '3.5rem', xl: '4rem' },
    lineHeight: 1,
    letterSpacing: '0.04em',
  }),
  subtitle: css({
    fontFamily: 'Inter, sans-serif',
    fontSize: { base: '0.875rem', sm: '0.95rem', md: '1rem', lg: '1.05rem' },
    lineHeight: { base: 1.6, md: 1.7 },
    color: 'rgba(255,255,255,0.75)',
    maxW: { base: '100%', lg: '55ch' },
  }),
  attributesGrid: css({
    display: 'grid',
    gridTemplateColumns: { 
      base: 'repeat(2, minmax(0, 1fr))', 
      sm: 'repeat(2, minmax(0, 1fr))',
      md: 'repeat(3, minmax(0, 1fr))',
      lg: 'repeat(3, minmax(0, 1fr))'
    },
    gap: { base: 2, sm: 3, md: 4 },
    mt: { base: 4, md: 5 },
    width: '100%',
  }),
  attributeCard: css({

    display: 'flex',
    flexDirection: 'column',
    gap: 1,
  }),
  attributeLabel: css({
    textTransform: 'uppercase',
    letterSpacing: '0.2em',
    fontSize: '0.65rem',
    color: 'rgba(255,255,255,0.5)',
  }),
  attributeValue: css({
    fontFamily: 'var(--font-bebas-neue), sans-serif',
    fontSize: { base: '1.4rem', sm: '1.6rem', md: '1.8rem', lg: '2rem' },
    letterSpacing: '0.04em',
  }),
  placeholderPanel: css({
    width: '100%',
    maxW: '900px',
    borderRadius: { base: '20px', md: '28px' },
    border: '1px solid rgba(255,255,255,0.25)',
    padding: { base: '32px', md: '48px' },
    textAlign: 'center',
    background: 'rgba(5,5,5,0.6)',
    backdropFilter: 'blur(16px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minH: '280px',
  }),
  placeholderText: css({
    fontSize: { base: '1rem', md: '1.2rem' },
    color: 'rgba(255,255,255,0.75)',
    letterSpacing: '0.15em',
    textTransform: 'uppercase',
  }),

  // Empty state - Minimaliste
  emptyMediaPanel: css({
    position: 'relative',
    width: '100%',
    maxW: { base: '100%', sm: '320px', md: '380px', lg: '420px', xl: '480px' },
    aspectRatio: '1 / 1',
    borderRadius: { base: '20px', sm: '24px', md: '28px', lg: '32px', xl: '36px' },
    overflow: 'hidden',
    isolation: 'isolate',
    bg: '#0d0d0c',
    boxShadow: { base: '0 15px 40px rgba(0,0,0,0.45)', md: '0 25px 60px rgba(0,0,0,0.55)' },
    alignSelf: 'center',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: '1px solid rgba(196, 196, 196, 0.1)',
  }),
  emptyStateIcon: css({
    fontFamily: 'var(--font-bebas-neue), sans-serif',
    fontSize: { base: '3rem', md: '4rem' },
    color: '#C4C4C4',
    opacity: 0.4,
    letterSpacing: '0.1em',
  }),
  emptyStateTitle: css({
    fontFamily: 'var(--font-bebas-neue), sans-serif',
    fontSize: { base: '2rem', sm: '2.5rem', md: '3rem', lg: '3.5rem', xl: '4rem' },
    lineHeight: 1,
    letterSpacing: '0.04em',
    color: '#ffffff',
  }),
  emptyStateSubtitle: css({
    fontFamily: 'Inter, sans-serif',
    fontSize: { base: '0.875rem', sm: '0.95rem', md: '1rem', lg: '1.05rem' },
    lineHeight: { base: 1.6, md: 1.7 },
    color: '#C4C4C4',
    maxW: { base: '100%', lg: '55ch' },
  }),
  // Loader state
  emptyStateLoader: css({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
  }),
  emptyStateLoaderDot: css({
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    background: '#C4C4C4',
    animation: 'dotPulse 1.4s ease-in-out infinite',
    '&:nth-child(1)': {
      animationDelay: '0s',
    },
    '&:nth-child(2)': {
      animationDelay: '0.2s',
    },
    '&:nth-child(3)': {
      animationDelay: '0.4s',
    },
  }),

  subscribeButton: css({
    width: '100%',
    padding: '10px 14px',
    borderRadius: '12px',
    border: 'none',
    background: 'linear-gradient(120deg, #ffffff 0%, #b3b3b3 100%)',
    color: '#050505',
    fontSize: '0.8rem',
    fontWeight: 600,
    letterSpacing: '0.15em',
    textTransform: 'uppercase',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    '&:hover': {
      transform: 'translateY(-1px)',
      boxShadow: '0 8px 20px rgba(255,255,255,0.15)',
    },
    '&:disabled': {
      opacity: 0.6,
      cursor: 'not-allowed',
      transform: 'none',
    },
  }),
  feedbackMessage: css({
    fontSize: '0.75rem',
    textAlign: 'center',
    padding: '6px 10px',
    borderRadius: '8px',
  }),
  feedbackSuccess: css({
    color: '#00ff94',
    background: 'rgba(0,255,148,0.1)',
    border: '1px solid rgba(0,255,148,0.2)',
  }),
  feedbackError: css({
    color: '#ff6b6b',
    background: 'rgba(255,107,107,0.1)',
    border: '1px solid rgba(255,107,107,0.2)',
  }),
  calendarSeparator: css({
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    margin: '4px 0',
    '&::before, &::after': {
      content: '""',
      flex: 1,
      height: '1px',
      background: 'rgba(255,255,255,0.15)',
    },
    '& span': {
      fontSize: '0.7rem',
      color: 'rgba(255,255,255,0.5)',
      textTransform: 'uppercase',
      letterSpacing: '0.1em',
      whiteSpace: 'nowrap',
    },
  }),
  calendarButtons: css({
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  }),
  calendarButton: css({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    width: '100%',
    padding: '10px 14px',
    borderRadius: '12px',
    border: '1px solid rgba(255,255,255,0.15)',
    background: 'rgba(255,255,255,0.03)',
    color: '#f5f4f3',
    fontSize: '0.75rem',
    fontWeight: 500,
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    '&:hover': {
      borderColor: 'rgba(255,255,255,0.3)',
      background: 'rgba(255,255,255,0.08)',
      transform: 'translateY(-1px)',
    },
    '&:active': {
      transform: 'translateY(0)',
    },
    '& svg': {
      flexShrink: 0,
      strokeWidth: 2,
    },
  }),
  calendarSection: css({
    display: 'flex',
    flexDirection: 'column',
    gap: { base: 3, md: 4 },
  }),
  loginPrompt: css({
    display: 'flex',
    flexDirection: 'column',
    gap: { base: 3, md: 4 },
  }),
  loginButton: css({
    width: '100%',
    padding: '10px 14px',
    borderRadius: '12px',
    border: 'none',
    background: 'linear-gradient(120deg, #ffffff 0%, #b3b3b3 100%)',
    color: '#050505',
    fontSize: '0.8rem',
    fontWeight: 600,
    letterSpacing: '0.15em',
    textTransform: 'uppercase',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    '&:hover': {
      transform: 'translateY(-1px)',
      boxShadow: '0 8px 20px rgba(255,255,255,0.15)',
    },
    '&:active': {
      transform: 'translateY(0)',
    },
  }),
};
